import { ArrowRight, ArrowUpRight, Binary, BookOpen, Braces, Check, CircleAlert, Code2, Eye, Filter, Gauge, GitBranch, Layers3, LockKeyhole, MousePointer2, Route, ScanSearch, ShieldCheck, Sparkles, TerminalSquare, X } from 'lucide-react';
import { Arena } from './Arena';

const experiments=[
 {slug:'agent-safety',n:'01',status:'LIVE',icon:ShieldCheck,title:'Agent safety gate',desc:'Can a typed evaluator stop a browser agent before an unsafe action executes?',type:'VERIFY',result:'2 / 4 correct',tone:'warn'},
 {slug:'content-firewall',n:'02',status:'NEXT',icon:Filter,title:'Content firewall',desc:'Turn natural-language boundaries into an inspectable feed policy with three competing judges.',type:'FILTER',result:'Designing the test',tone:'green'},
 {slug:'design-audit',n:'03',status:'QUEUED',icon:ScanSearch,title:'Design requirements audit',desc:'Separate deterministic UI checks from the fuzzy requirements that need semantic judgment.',type:'SCORE',result:'Protocol draft',tone:'dim'},
 {slug:'action-router',n:'04',status:'QUEUED',icon:Route,title:'Bounded action router',desc:'Map ambiguous intent to one allowlisted action, then refuse below the policy threshold.',type:'CHOOSE',result:'Protocol draft',tone:'dim'}
];
const Nav=()=> <nav className="lab-nav"><a className="mark" href="/"><ShieldCheck/>JEV <span>/ LAB</span></a><div className="navlinks"><a href="/experiments/content-firewall">EXPERIMENTS</a><a href="/learn">LEARN</a><a href="/about">ABOUT</a><a className="source" href="https://github.com/mjyoke1111/jev-agent-safety-arena">SOURCE <ArrowUpRight/></a></div></nav>;
const Footer=()=> <footer className="lab-footer"><div className="mark"><ShieldCheck/>JEV <span>/ LAB</span></div><p>Independent experiments. Not affiliated with TypeSafe AI.</p><a className="coffee" href="https://buymeacoffee.com/mjyoke1111" target="_blank" rel="noopener noreferrer">Enjoy the project? Buy me a coffee ↗</a></footer>;
function Home(){return <main className="lab"><Nav/><header className="lab-hero"><div className="hero-kicker"><i/> INDEPENDENT SYSTEM ONE EXPERIMENTS</div><h1>Decisions,<br/><em>under pressure.</em></h1><div className="hero-bottom"><p>Jev Lab tests one narrow idea: where does a typed semantic judgment layer help software, and where does it fail?</p><div className="hero-proof"><span>04<br/><small>EXPERIMENTS</small></span><span>01<br/><small>LIVE RUN</small></span><span>100%<br/><small>OPEN METHODS</small></span></div></div><div className="signal" aria-hidden="true"><span/><span/><span/><span/><b>?</b></div></header>
<section className="control-strip"><div><small>STATE</small><b>What the system knows</b><Braces/></div><i><ArrowRight/></i><div><small>TYPED QUESTION</small><b>Choice · Score · Boolean</b><Binary/></div><i><ArrowRight/></i><div><small>PROBABILITY</small><b>Measured uncertainty</b><Gauge/></div><i><ArrowRight/></i><div><small>POLICY</small><b>Code decides what happens</b><GitBranch/></div></section>
<section className="experiment-section"><div className="lab-heading"><div><small>THE TEST BENCH</small><h2>Experiments, not showcases.</h2></div><p>Every lab exposes its inputs, typed questions, probabilities, deterministic policy, outcome check, and failure modes.</p></div><div className="experiment-grid">{experiments.map(e=>{const I=e.icon;return <a className={`experiment-card ${e.tone}`} href={e.slug==='agent-safety'?'/arena':`/experiments/${e.slug}`} key={e.slug}><div className="exp-top"><span>{e.n}</span><b>{e.status}</b></div><I/><small>{e.type}</small><h3>{e.title}</h3><p>{e.desc}</p><div className="exp-result"><span>{e.result}</span><ArrowUpRight/></div></a>})}</div></section>
<section className="thesis"><div><small>THE THESIS</small><h2>Generators make.<br/>Jev <em>judges.</em><br/>Code acts.</h2></div><div className="thesis-copy"><p>Jev is most interesting as a bounded control layer: classify, filter, select, rank, or verify. It is not the browser, the designer, or the agent.</p><p>The hard part is not receiving a probability. It is defining the question, calibrating the threshold, and checking the real-world outcome independently.</p><a href="/learn">PATTERNS AND ANTI-PATTERNS <ArrowRight/></a></div></section>
<section className="truth-block"><CircleAlert/><div><small>RUN 001 / SAFETY ARENA</small><h2>The harness worked.<br/><span>The gate did not.</span></h2><p>Jev and the mini baseline both passed two benign tasks and missed both injection cases. One miss was marked safe at 94% confidence.</p></div><a href="/arena">INSPECT THE RUN <ArrowRight/></a></section><Footer/></main>}
function Experiment({slug}:{slug:string}){const e=experiments.find(x=>x.slug===slug)||experiments[1];const I=e.icon;return <main className="lab"><Nav/><header className="protocol-hero"><div><small>EXPERIMENT {e.n} / {e.status}</small><I/><h1>{e.title}</h1><p>{e.desc}</p></div><aside><span>PROTOCOL STATUS</span><b>{e.status==='NEXT'?'DESIGN REVIEW':'NOT YET RUN'}</b><small>No outcome is shown until a real run completes.</small></aside></header><section className="protocol"><div className="protocol-index"><span>01 PROBLEM</span><span>02 DEMO</span><span>03 STATE</span><span>04 QUESTIONS</span><span>05 POLICY</span><span>06 OUTCOME</span><span>07 LIMITS</span></div><div className="protocol-body"><Block n="01" title="Problem"><p>{slug==='content-firewall'?'Keyword filters miss meaning. Generative moderation can be slow, expensive, and difficult to constrain. This test asks whether typed semantic decisions can enforce a human-readable feed rule without hiding legitimate posts.':'This experiment isolates one bounded judgment inside a larger software loop.'}</p></Block><Block n="02" title="Interactive demo"><div className="demo-placeholder"><Eye/><span>LIVE FIXTURE</span><b>Demo activates only after the protocol and outcome checker are locked.</b></div></Block><Block n="03" title="Input / state"><pre>{`{
  "policy": "hide fake urgency and engagement bait",
  "post": "...",
  "context": { "author_followed": false }
}`}</pre></Block><Block n="04" title="Typed questions"><div className="question"><span>BOOLEAN</span><b>Does this post violate the policy?</b><small>P(true) required</small></div><div className="question"><span>SCORE</span><b>How costly would a false positive be?</b><small>low / medium / high</small></div></Block><Block n="05" title="Deterministic policy"><pre>{`collapse = violates >= 0.82 && falsePositiveRisk < 1.4
review   = violates >= 0.55 && !collapse
show     = otherwise`}</pre></Block><Block n="06" title="Independent outcome"><p>A labeled fixture set scores precision, recall, disagreements, and false positives. The evaluator never grades itself.</p></Block><Block n="07" title="Limits"><p>Natural-language policies are unstable. Probabilities require calibration. For fixed taxonomies with training data, rules or a local classifier may be faster, cheaper, and more private.</p></Block></div></section><Footer/></main>}
function Block({n,title,children}:{n:string,title:string,children:any}){return <article className="protocol-block"><small>{n}</small><h2>{title}</h2><div>{children}</div></article>}
function Learn(){return <main className="lab"><Nav/><section className="text-page"><small>FIELD GUIDE</small><h1>Use the smallest judge<br/>that can do the job.</h1><div className="versus"><article><Check/><h2>Good Jev shapes</h2><p>Changing semantic taxonomies. Bounded choices. Fuzzy requirements. Cheap review gates. Uncertain cases routed to people.</p></article><article><X/><h2>Bad Jev shapes</h2><p>Text generation. Tool execution. Stable labels with ample training data. Hard rules already expressible in code. Unreviewed high-stakes automation.</p></article></div></section><Footer/></main>}
function About(){return <main className="lab"><Nav/><section className="text-page"><small>ABOUT THIS LAB</small><h1>Independent by design.</h1><p className="page-lede">Jev Lab is an experiment-silo project. It is not affiliated with, sponsored by, or endorsed by TypeSafe AI. Vendor claims, community reports, and results measured here are labeled separately.</p><div className="about-grid"><article><LockKeyhole/><h2>Privacy</h2><p>Fixtures use synthetic data. Secrets never enter published run artifacts.</p></article><article><Code2/><h2>Reproducibility</h2><p>Runs carry model routes, timestamps, inputs, usage, and immutable JSON evidence.</p></article><article><BookOpen/><h2>Restraint</h2><p>One run is evidence of one run. It is never promoted as a benchmark.</p></article></div></section><Footer/></main>}
export function App(){const path=location.pathname;if(path==='/arena')return <Arena/>;if(path==='/learn')return <Learn/>;if(path==='/about')return <About/>;if(path.startsWith('/experiments/'))return <Experiment slug={path.split('/').pop()||'content-firewall'}/>;return <Home/>}
