import {useEffect,useMemo,useState} from 'react'; import {Activity,ArrowUpRight,CheckCircle2,CircleAlert,Clock3,Code2,ShieldCheck,Terminal,TriangleAlert} from 'lucide-react'; import type {Decision,Run} from './types';
const fmt=(n:number,d=0)=>n.toLocaleString(undefined,{maximumFractionDigits:d});
const Stat=({label,value,sub,accent=false}:{label:string,value:string,sub:string,accent?:boolean})=><div className="stat"><span>{label}</span><strong className={accent?'accent':''}>{value}</strong><small>{sub}</small></div>;
const Empty=()=> <section className="empty"><div className="radar"><ShieldCheck size={36}/><i/><i/></div><div><p className="eyebrow">AWAITING EVIDENCE</p><h2>No run data yet.</h2><p>Run the harness with valid model credentials. Metrics appear only after a completed browser evaluation.</p><code>npm run harness</code></div></section>;
export function Arena(){const [run,setRun]=useState<Run|null>(null);const [mode,setMode]=useState<'jev'|'baseline'>('jev');const [error,setError]=useState(false);useEffect(()=>{fetch('/runs/latest.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(setRun).catch(()=>setError(true))},[]);const rows=useMemo(()=>run?.decisions.filter(d=>d.actor===mode)??[],[run,mode]);const success=rows.length?100*rows.filter(x=>x.correct).length/rows.length:0;const injected=rows.filter(x=>x.caseId.startsWith('inject-'));const caught=injected.filter(x=>x.correct).length;const med=rows.length?[...rows].sort((a,b)=>a.latencyMs-b.latencyMs)[Math.floor(rows.length/2)].latencyMs:0;const cost=rows.reduce((a,b)=>a+b.costUsd,0);return <main>
<nav><div className="mark"><ShieldCheck/>JEV <span>/ SAFETY ARENA</span></div><a href="/" aria-label="Jev Lab home">JEV LAB <ArrowUpRight size={14}/></a></nav>
<header><div className="hero-copy"><p className="eyebrow"><span className="pulse"/> BROWSER AGENT EVALUATION HARNESS</p><h1>Trust the action.<br/><em>Not the page.</em></h1><p className="lede">A reproducible arena for testing browser agents against prompt injection. A planner proposes. Jev chooses. Every decision leaves evidence.</p><div className="badges"><span><Code2/>PLAYWRIGHT</span><span><ShieldCheck/>TYPED DECISIONS</span><span><Activity/>LIVE TELEMETRY</span></div></div><div className="terminal-card"><div className="terminal-head"><span/><span/><span/><b>agent-loop.ts</b></div><pre><i>01</i> <b>const</b> plan = <u>await</u> planner.observe(page){'\n'}<i>02</i> <b>const</b> next = <u>await</u> jev.choose(actions){'\n'}<i>03</i> <b>const</b> gate = <u>await</u> jev.isSafe(next){'\n'}<i>04</i>{'\n'}<i>05</i> <span>{'if (gate.safe && gate.confidence > .7) {'}</span>{'\n'}<i>06</i> {'  '}<u>await</u> page.execute(next){'\n'}<i>07</i> <span>{'}'}</span></pre><div className="terminal-foot"><span><i/> POLICY GATE ACTIVE</span><b>typesafe-ai/jev</b></div></div></header>
<section className="dashboard"><div className="section-head"><div><p className="eyebrow">LATEST VERIFIED RUN</p><h2>Decision telemetry</h2></div><div className="toggle"><button className={mode==='jev'?'on':''} onClick={()=>setMode('jev')}>Jev</button><button className={mode==='baseline'?'on':''} onClick={()=>setMode('baseline')}>Mini baseline</button></div></div>
{!run?<Empty/>:<><div className="run-meta"><span><CheckCircle2/> COMPLETE</span><span>{run.runId}</span><span>{new Date(run.createdAt).toLocaleString()}</span></div><div className="stats"><Stat label="Task success" value={`${fmt(success,1)}%`} sub={`${rows.filter(x=>x.correct).length} / ${rows.length} decisions correct`} accent/><Stat label="Injection catch rate" value={`${caught}/${injected.length}`} sub="hostile cases correctly stopped"/><Stat label="Median latency" value={`${fmt(med)} ms`} sub="model round-trip"/><Stat label="Total cost" value={`$${cost.toFixed(4)}`} sub="provider-reported token usage"/></div><div className="grid"><div className="panel decisions"><div className="panel-head"><h3>Decision stream</h3><span>{rows.length} EVENTS</span></div>{rows.map((d:Decision)=><div className="decision" key={d.id}><span className={d.safe?'safe':'blocked'}>{d.safe?<CheckCircle2/>:<TriangleAlert/>}</span><div><b>{d.caseTitle}</b><p>{d.action}</p></div><div className="numbers"><b>{Math.round(d.confidence*100)}%</b><small>{d.latencyMs} ms · ${d.costUsd.toFixed(5)}</small></div></div>)}</div><div className="panel"><div className="panel-head"><h3>Confidence distribution</h3><span>ACTUAL</span></div><div className="bars">{[.5,.6,.7,.8,.9].map((v,i)=>{const n=rows.filter(x=>x.confidence>=v&&x.confidence<v+.1).length;return <div key={v}><span style={{height:`${Math.max(3,n/Math.max(rows.length,1)*180)}px`}}/><b>{n}</b><small>{Math.round(v*100)}–{Math.round((v+.1)*100)}</small></div>})}</div></div></div></>}
</section>
<section className="method"><div><p className="eyebrow">THE ARENA</p><h2>Benign tasks.<br/>Hostile instructions.</h2></div><div className="method-grid"><article><b>01</b><Terminal/><h3>Observe</h3><p>Playwright captures page state and exposes a constrained action set.</p></article><article><b>02</b><Activity/><h3>Propose</h3><p>A configurable generative model creates the plan and candidate actions.</p></article><article><b>03</b><ShieldCheck/><h3>Evaluate</h3><p>Jev selects the next action, then independently scores whether it is safe.</p></article><article><b>04</b><Clock3/><h3>Measure</h3><p>Latency, usage, confidence, correctness and cost are written from the run.</p></article></div></section>
<footer><div className="mark"><ShieldCheck/>JEV <span>/ SAFETY ARENA</span></div><p>{error?'No results loaded. Run the harness to generate evidence.':'Metrics loaded from the latest completed run.'}</p><a className="coffee" href="https://buymeacoffee.com/mjyoke1111" target="_blank" rel="noopener noreferrer">Enjoy the project? Buy me a coffee ↗</a><span>NO SYNTHETIC BENCHMARKS</span></footer></main>}
